### ISSUE TITLE
search theme is broken

### ISSUE THREAD

**Issue by whiteworthy** [lollilol/darker-discord-fixes#1]
search results displays as default gray

**Comment by lollilol** [comment]
can you share a screenshot? it works fine for me..

**Comment by whiteworthy** [comment]
![image](https://user-images.githubusercontent.com/11664917/113486018-075d8f80-9487-11eb-9ea4-0d12b5505630.png)
discord stable

**Comment by lollilol** [comment]
sorry for not answering for 12 days lol i had stuff to do
anyways, its working for me, and i dont have any other themes or custom css so idk whats wrong lol
![image](https://user-images.githubusercontent.com/38194372/114855481-4fb17180-9de6-11eb-8dc4-86343ceb9172.png)
